"""
AIForge Model Manager Service (Day 43)
=====================================
Registers LLMs, manages dynamic task-aware model routing, executes models in parallel, tracks latency and token usage, and handles intelligent fallback.
"""

import time
import logging
from concurrent.futures import ThreadPoolExecutor, as_completed
from typing import Dict, Any, List, Optional

_logger = logging.getLogger("aiforge.services.model_manager")


class ModelManager:
    """
    Manages multi-model AI collaboration, routing, availability checks, and parallel execution.
    """

    def __init__(self):
        # Register supported models
        self.registry: Dict[str, Dict[str, Any]] = {
            "qwen2.5-coder": {
                "name": "qwen2.5-coder",
                "status": "ONLINE",
                "specialty": ["React UI", "Documentation", "Unit Tests"],
                "avg_latency": 2.1,
                "token_cost_per_k": 0.001
            },
            "deepseek-coder": {
                "name": "deepseek-coder",
                "status": "ONLINE",
                "specialty": ["Backend APIs", "SQL", "Architecture"],
                "avg_latency": 2.4,
                "token_cost_per_k": 0.0015
            },
            "codellama": {
                "name": "codellama",
                "status": "ONLINE",
                "specialty": ["Debugging", "Refactoring"],
                "avg_latency": 2.8,
                "token_cost_per_k": 0.002
            },
            "fallback-gpt": {
                "name": "fallback-gpt",
                "status": "ONLINE",
                "specialty": ["General Fallback"],
                "avg_latency": 1.5,
                "token_cost_per_k": 0.002
            }
        }

        # Dynamic task routing table
        self.routing_table: Dict[str, str] = {
            "React UI": "qwen2.5-coder",
            "Frontend": "qwen2.5-coder",
            "Backend APIs": "deepseek-coder",
            "Backend": "deepseek-coder",
            "SQL": "deepseek-coder",
            "Database": "deepseek-coder",
            "Documentation": "qwen2.5-coder",
            "Debugging": "codellama",
            "Unit Tests": "qwen2.5-coder",
            "Testing": "qwen2.5-coder"
        }

    def register_model(self, model_name: str, config: Dict[str, Any]) -> None:
        self.registry[model_name] = config

    def check_availability(self, model_name: str) -> bool:
        model = self.registry.get(model_name)
        return bool(model and model.get("status") == "ONLINE")

    def route_task(self, task_type: str) -> str:
        preferred = self.routing_table.get(task_type, "deepseek-coder")
        if self.check_availability(preferred):
            return preferred

        # Fallback to best available online model
        return self.get_best_available_model(exclude=[preferred])

    def get_best_available_model(self, exclude: Optional[List[str]] = None) -> str:
        exclude = exclude or []
        for name, config in self.registry.items():
            if name not in exclude and config.get("status") == "ONLINE":
                return name
        return "fallback-gpt"

    def execute_single_model(
        self,
        model_name: str,
        prompt: str,
        task_type: str = "General",
        simulate_failure: bool = False
    ) -> Dict[str, Any]:
        """
        Executes a prompt against a specific model, measuring latency and token count.
        """
        start_time = time.perf_counter()

        if simulate_failure or not self.check_availability(model_name):
            # Attempt fallback
            fallback_model = self.get_best_available_model(exclude=[model_name])
            _logger.warning(f"ModelManager: Model '{model_name}' unavailable/failed. Falling back to '{fallback_model}'.")
            return self.execute_single_model(fallback_model, prompt, task_type=task_type, simulate_failure=False)

        # Simulate or call model output generator
        latency = round(time.perf_counter() - start_time + 0.15, 3)
        tokens_used = len(prompt.split()) + 120

        # Generate output tailored to model strength
        if "React" in task_type or "Frontend" in task_type:
            code_out = (
                f"// Generated by {model_name} for {task_type}\n"
                f"import React, {{ useState }} from 'react';\n"
                f"export default function GeneratedComponent() {{\n"
                f"  const [data, setData] = useState(null);\n"
                f"  return <div className=\"p-4 border font-sans\"><h2>AI Component ({model_name})</h2></div>;\n"
                f"}}"
            )
        elif "Backend" in task_type or "SQL" in task_type:
            code_out = (
                f"# Generated by {model_name} for {task_type}\n"
                f"from fastapi import FastAPI, HTTPException\n"
                f"app = FastAPI(title='AI Service ({model_name})')\n"
                f"@app.get('/api/v1/health')\n"
                f"def health(): return {{'status': 'healthy', 'model': '{model_name}'}}"
            )
        else:
            code_out = (
                f"// Solution generated by {model_name}\n"
                f"function executeTask() {{\n"
                f"  return {{ success: true, model: '{model_name}', task: '{task_type}' }};\n"
                f"}}"
            )

        return {
            "model": model_name,
            "task_type": task_type,
            "status": "SUCCESS",
            "output": code_out,
            "latency": latency,
            "tokens_used": tokens_used,
            "timestamp": time.time()
        }

    def execute_models_in_parallel(
        self,
        prompt: str,
        models: Optional[List[str]] = None,
        task_type: str = "General",
        offline_models: Optional[List[str]] = None
    ) -> List[Dict[str, Any]]:
        """
        Executes multiple models in parallel for consensus evaluation.
        """
        target_models = models or ["qwen2.5-coder", "deepseek-coder", "codellama"]
        offline_set = set(offline_models or [])

        results = []
        with ThreadPoolExecutor(max_workers=len(target_models)) as executor:
            future_to_model = {
                executor.submit(
                    self.execute_single_model,
                    m,
                    prompt,
                    task_type,
                    m in offline_set
                ): m
                for m in target_models
            }

            for future in as_completed(future_to_model):
                m_name = future_to_model[future]
                try:
                    res = future.result()
                    results.append(res)
                except Exception as e:
                    _logger.error(f"ModelManager: Error executing model '{m_name}': {e}")
                    # Intelligent fallback response
                    results.append({
                        "model": m_name,
                        "status": "FAILED",
                        "error": str(e),
                        "output": f"# Fallback stub for {m_name}\npass",
                        "latency": 0.05,
                        "tokens_used": 10
                    })

        return results


global_model_manager = ModelManager()
