"""
AIForge Real Project Multi-File Directory Builder
=================================================
Assembles multi-file project workspace:
Formula-Racing/
├── frontend/
│   ├── App.jsx
│   ├── Home.jsx
│   ├── Cars.jsx
│   ├── Gallery.jsx
│   └── Login.jsx
├── backend/
│   ├── main.py
│   ├── auth.py
│   ├── cars.py
│   └── drivers.py
├── database/
│   └── schema.sql
├── docs/
├── docker/
└── README.md
"""

import json
import hashlib
import logging
from pathlib import Path
from typing import Dict, Any, List, Optional

_logger = logging.getLogger("aiforge.builder")


from backend.validation.code_extractor import extract_files_from_agent_output
from backend.validation.generated_file_validator import global_file_validator


class StructuredProjectBuilder:
    """
    Assembles structured multi-file project workspace directories.
    """

    def assemble_real_project(
        self,
        project_name: str,
        plan_json: Dict[str, Any],
        arch_json: Dict[str, Any],
        frontend_code: str = "",
        backend_code: str = "",
        database_code: str = "",
        testing_code: str = "",
        docs_code: str = ""
    ) -> Dict[str, Any]:
        _logger.info(f"StructuredProjectBuilder: Assembling real multi-file project for '{project_name}'...")

        safe_name = "".join([c if c.isalnum() or c in " -_" else "_" for c in project_name]).strip()
        files_manifest: Dict[str, str] = {}
        invalid_files: List[str] = []

        # 1. Extract multi-file outputs from each agent
        for agent_name, raw_code in [
            ("frontend", frontend_code),
            ("backend", backend_code),
            ("database", database_code),
            ("testing", testing_code),
            ("documentation", docs_code),
        ]:
            if not raw_code:
                continue
            extracted = extract_files_from_agent_output(raw_code, agent_name=agent_name)
            for path, content in extracted.items():
                # Validate before preserving
                val = global_file_validator.validate_file(path, content, agent=agent_name)
                if val.is_valid:
                    files_manifest[path] = content
                else:
                    invalid_files.append(path)
                    if path not in files_manifest:
                        # If invalid but non-empty, keep content for potential regeneration
                        files_manifest[path] = content

        # 2. Infrastructure & system configs
        if "docker/Dockerfile" not in files_manifest and "Dockerfile" not in files_manifest:
            files_manifest["docker/Dockerfile"] = (
                "FROM python:3.11-alpine\nWORKDIR /app\nCOPY . .\n"
                "CMD [\"python\", \"-m\", \"uvicorn\", \"backend.main:app\", \"--host\", \"0.0.0.0\", \"--port\", \"8000\"]\n"
            )

        if "README.md" not in files_manifest:
            files_manifest["README.md"] = f"# {project_name}\n\nGenerated by AIForge Autonomous Engineering Platform.\n"

        target_dir = Path("generated_projects") / safe_name

        return {
            "project_name": project_name,
            "safe_dir_name": safe_name,
            "project_path": str(target_dir),
            "total_files": len(files_manifest),
            "invalid_files": invalid_files,
            "file_structure": list(files_manifest.keys()),
            "manifest": files_manifest
        }

    def write_project_to_disk(
        self,
        project_name: str,
        files_manifest: Dict[str, str],
        base_dir: str = "generated_projects"
    ) -> Path:
        """
        Safely writes files from manifest to generated_projects/<ProjectName>/ on disk.
        Enforces strict path traversal security checks to prevent writing outside target directory.
        """
        safe_name = "".join([c if c.isalnum() or c in "-_" else "_" for c in project_name]).strip("_") or "AIForgeProject"
        base_path = Path(base_dir).resolve()
        target_dir = (base_path / safe_name).resolve()

        # Security check: ensure target_dir is strictly inside base_path
        if not str(target_dir).startswith(str(base_path)):
            raise ValueError(f"Unsafe project directory path: {target_dir}")

        target_dir.mkdir(parents=True, exist_ok=True)

        for rel_path_str, content in files_manifest.items():
            clean_rel = rel_path_str.replace("\\", "/").lstrip("/")
            if rel_path_str.startswith("/") or rel_path_str.startswith("\\"):
                raise ValueError(f"Absolute path rejected: {rel_path_str}")

            dest_path = (target_dir / clean_rel).resolve()

            # Path traversal security check
            if not str(dest_path).startswith(str(target_dir)):
                raise ValueError(f"Security Warning: Path traversal detected for path '{rel_path_str}'")

            dest_path.parent.mkdir(parents=True, exist_ok=True)
            dest_path.write_text(content, encoding="utf-8")

            # Write -> Read-Back Verification (Checksum Check)
            readback_content = dest_path.read_text(encoding="utf-8")
            expected_hash = hashlib.sha256(content.encode("utf-8")).hexdigest()
            actual_hash = hashlib.sha256(readback_content.encode("utf-8")).hexdigest()

            if expected_hash != actual_hash:
                _logger.error(f"FileIntegrityError: Hash mismatch after disk write for '{clean_rel}'")
                raise IOError(f"FileIntegrityError: Disk write verification failed for '{clean_rel}'")

        _logger.info(f"Successfully wrote and verified {len(files_manifest)} files to disk at '{target_dir}'")
        return target_dir


global_structured_project_builder = StructuredProjectBuilder()

