"""
AIForge Real Project Multi-File Directory Builder
=================================================
Assembles multi-file project workspace:
Formula-Racing/
├── frontend/
│   ├── App.jsx
│   ├── Home.jsx
│   ├── Cars.jsx
│   ├── Gallery.jsx
│   └── Login.jsx
├── backend/
│   ├── main.py
│   ├── auth.py
│   ├── cars.py
│   └── drivers.py
├── database/
│   └── schema.sql
├── docs/
├── docker/
└── README.md
"""

import json
import logging
from pathlib import Path
from typing import Dict, Any, List, Optional

_logger = logging.getLogger("aiforge.builder")


class StructuredProjectBuilder:
    """
    Assembles structured multi-file project workspace directories.
    """

    def assemble_real_project(
        self,
        project_name: str,
        plan_json: Dict[str, Any],
        arch_json: Dict[str, Any],
        frontend_code: str,
        backend_code: str,
        database_code: str,
        testing_code: str,
        docs_code: str
    ) -> Dict[str, Any]:
        _logger.info(f"StructuredProjectBuilder: Assembling real multi-file project for '{project_name}'...")

        safe_name = "".join([c if c.isalnum() or c in " -_" else "_" for c in project_name]).strip()
        files_manifest = {
            "frontend/src/App.jsx": frontend_code or "// React App Root",
            "frontend/src/components/Navbar.jsx": "// React Navbar Component",
            "frontend/src/pages/Home.jsx": "// React Home Page",
            "backend/main.py": backend_code or "# FastAPI Main App",
            "backend/models.py": "# SQLAlchemy Models",
            "backend/auth.py": "# JWT Authentication Middleware",
            "database/schema.sql": database_code or "-- SQL Database Schema",
            "tests/test_main.py": testing_code or "# Pytest Integration Tests",
            "docs/API.md": "# API Documentation",
            "docker/Dockerfile": "FROM python:3.11-alpine\nWORKDIR /app\nCOPY . .\nCMD [\"python\", \"-m\", \"uvicorn\", \"backend.main:app\"]",
            "README.md": docs_code or f"# {project_name}\n\nGenerated by AIForge Autonomous Engineering Platform."
        }

        return {
            "project_name": project_name,
            "safe_dir_name": safe_name,
            "total_files": len(files_manifest),
            "file_structure": list(files_manifest.keys()),
            "manifest": files_manifest
        }

    def write_project_to_disk(
        self,
        project_name: str,
        files_manifest: Dict[str, str],
        base_dir: str = "generated_projects"
    ) -> Path:
        """
        Safely writes files from manifest to generated_projects/<ProjectName>/ on disk.
        Enforces strict path traversal security checks to prevent writing outside target directory.
        """
        safe_name = "".join([c if c.isalnum() or c in "-_" else "_" for c in project_name]).strip("_") or "AIForgeProject"
        base_path = Path(base_dir).resolve()
        target_dir = (base_path / safe_name).resolve()

        # Security check: ensure target_dir is strictly inside base_path
        if not str(target_dir).startswith(str(base_path)):
            raise ValueError(f"Unsafe project directory path: {target_dir}")

        target_dir.mkdir(parents=True, exist_ok=True)

        for rel_path_str, content in files_manifest.items():
            clean_rel = rel_path_str.replace("\\", "/").lstrip("/")
            if rel_path_str.startswith("/") or rel_path_str.startswith("\\"):
                raise ValueError(f"Absolute path rejected: {rel_path_str}")

            dest_path = (target_dir / clean_rel).resolve()

            # Path traversal security check
            if not str(dest_path).startswith(str(target_dir)):
                raise ValueError(f"Security Warning: Path traversal detected for path '{rel_path_str}'")

            dest_path.parent.mkdir(parents=True, exist_ok=True)
            dest_path.write_text(content, encoding="utf-8")

        _logger.info(f"Successfully wrote {len(files_manifest)} files to disk at '{target_dir}'")
        return target_dir


global_structured_project_builder = StructuredProjectBuilder()

