import ast
import json
import logging
import re
from pathlib import Path
from typing import Dict, Any, List

from backend.validation.generated_file_validator import global_file_validator

logger = logging.getLogger("aiforge.services.project_validator")

# Common patterns for API keys and secrets
SECRET_PATTERNS = [
    # General secret / password / key assignment
    r"\b(password|secret|api_key|token|passwd|private_key|aws_key|auth_key|jwt_secret)\s*=\s*['\"]([^'\"]{8,})['\"]",
    # Specific signatures: e.g. OpenAI keys, AWS keys
    r"\b(sk-[a-zA-Z0-9\-]{20,})\b",
    r"\b(AIza[a-zA-Z0-9_\\\-]{35})\b",
    r"mongodb\+srv://[^:]+:[^@]+@\S+",
]

# Standard placeholder terms that are NOT actual secrets
PLACEHOLDERS = {
    "placeholder", "your_", "my_", "example", "secret", "password", "token", "key", 
    "db_url", "database", "admin", "root", "localhost", "127.0.0.1", "foo", "bar",
    "replace", "dummy", "test", "todo"
}


class ProjectValidator:
    """
    ProjectValidator executes structural, syntactic, configuration, and security checks on assembled files.
    - Evaluates technology-aware completeness (FastAPI, React, SQL, etc.).
    - Detects empty critical files and placeholder templates.
    - Conducts syntax validations (Python AST, JSON parser, basic JS structure).
    - Scans for hardcoded secrets and redacts them in reports.
    - Calculates a transparent overall Quality Score and Status.
    """

    def validate_project(self, files_map: Dict[str, str], manifest: Dict[str, Any]) -> Dict[str, Any]:
        logger.info("[VALIDATOR] Starting project validation pipeline")

        errors: List[str] = []
        warnings: List[str] = []
        file_validations: Dict[str, Any] = {}

        # 1. Technology-Aware File Existence checks
        self._check_technology_structure(files_map, errors, warnings)

        # 2. Duplicate and Conflict summary checks from Manifest
        self._check_manifest_anomalies(manifest, errors, warnings)

        # 3. File content validation (Syntax, Placeholders, Empty check, Secrets)
        empty_files: List[str] = []
        secrets_detected: List[Dict[str, Any]] = []

        # Find file metadata from manifest to trace which agent generated it
        agent_by_path = {f["path"]: f["agent"] for f in manifest.get("files", [])}

        for path, content in files_map.items():
            agent = agent_by_path.get(path, "Unknown")
            
            # Syntax & general checks
            res = global_file_validator.validate_file(path, content, agent=agent)
            
            # Record status
            file_validations[path] = {
                "is_valid": res.is_valid,
                "status": res.status,
                "errors": res.errors,
                "warnings": res.warnings,
                "agent": agent
            }

            if not res.is_valid:
                # Classify empty critical files
                if res.status == "INVALID_EMPTY":
                    empty_files.append(path)
                    is_critical = self._is_critical_file(path)
                    msg = f"File '{path}' is empty (Generated by: {agent} Agent)."
                    if is_critical:
                        errors.append(f"CRITICAL: {msg}")
                    else:
                        warnings.append(msg)
                else:
                    for err in res.errors:
                        errors.append(f"Syntax/Structure error in '{path}': {err} (Generated by: {agent} Agent)")
            
            for warn in res.warnings:
                warnings.append(f"Warning in '{path}': {warn} (Generated by: {agent} Agent)")

            # Configuration specific validations
            self._validate_configs(path, content, errors, warnings)

            # Secret scan check
            detected = self._scan_secrets(path, content)
            if detected:
                secrets_detected.extend(detected)
                for sec in detected:
                    errors.append(f"CRITICAL: Potential hardcoded secret detected in '{path}' at line {sec['line']}. Value redacted: [REDACTED].")

        # 4. Compute Transparent Quality Score
        score, status = self._compute_quality_score(errors, warnings, len(files_map))

        validation_summary = {
            "status": status,
            "score": score,
            "errors": errors,
            "warnings": warnings,
            "details": {
                "total_files": len(files_map),
                "empty_files_count": len(empty_files),
                "empty_files": empty_files,
                "secrets_detected_count": len(secrets_detected),
                "secrets_detected": [
                    {"path": s["path"], "line": s["line"], "pattern": s["pattern"]} for s in secrets_detected
                ],
                "file_validations": file_validations
            }
        }

        # Update manifest validation dictionary
        manifest["validation"] = {
            "passed": status != "FAIL",
            "errors": len(errors),
            "warnings": len(warnings)
        }

        logger.info(f"[VALIDATOR] Validation completed. Status={status}, Score={score}, Errors={len(errors)}")
        return validation_summary

    def _is_critical_file(self, path: str) -> bool:
        """Determines if a file is critical to application runtime."""
        critical_names = ["main.py", "App.jsx", "package.json", "requirements.txt", "schema.sql"]
        p = Path(path)
        return p.name in critical_names

    def _check_technology_structure(self, files_map: Dict[str, str], errors: List[str], warnings: List[str]):
        """Runs technology-aware framework validations to check for missing expected entrypoints."""
        has_python = any(p.endswith(".py") for p in files_map)
        has_js = any(p.endswith(".js") or p.endswith(".jsx") or p.endswith(".ts") or p.endswith(".tsx") for p in files_map)
        has_sql = any(p.endswith(".sql") for p in files_map)

        # Python/FastAPI Backend requirements
        if has_python:
            if not any(p.endswith("main.py") or p.endswith("app.py") for p in files_map):
                warnings.append("Missing entry point for Python application (e.g. backend/main.py or app.py).")
            if "backend/requirements.txt" not in files_map and "requirements.txt" not in files_map and "pyproject.toml" not in files_map:
                warnings.append("Missing Python dependency declaration file (requirements.txt or pyproject.toml).")

        # React/JS Frontend requirements
        if has_js:
            if "frontend/package.json" not in files_map and "package.json" not in files_map:
                warnings.append("Missing Node package declaration file (package.json).")
            if not any("App.jsx" in p or "App.js" in p or "main.jsx" in p or "index.html" in p for p in files_map):
                warnings.append("Missing main React entry point (App.jsx / main.jsx / index.html).")

        # Database schema requirements
        if has_sql:
            if not any("schema.sql" in p or "seed.sql" in p for p in files_map):
                warnings.append("Missing database schema design script (schema.sql).")

        # Documentation
        if "README.md" not in files_map:
            warnings.append("Missing project README.md overview documentation file.")

    def _check_manifest_anomalies(self, manifest: Dict[str, Any], errors: List[str], warnings: List[str]):
        """Inspects structural assembly alerts such as agent output conflicts or duplicates."""
        conflicts = manifest.get("conflicts", [])
        for c in conflicts:
            errors.append(f"Assembly Conflict: File '{c['path']}' was outputted with different content by multiple agents: {list(c['sources'].keys())}.")

        duplicates = manifest.get("duplicates", [])
        for d in duplicates:
            warnings.append(f"Assembly Warning: Duplicate copies of '{d['path']}' were outputted by agents {d['agents']}.")

    def _validate_configs(self, path: str, content: str, errors: List[str], warnings: List[str]):
        """Runs lint-like checks on config files to ensure structure and block accidental hardcoded values."""
        name = Path(path).name

        # package.json
        if name == "package.json":
            try:
                data = json.loads(content)
                if not data.get("name"):
                    warnings.append("Config warning in package.json: 'name' field is missing or empty.")
                if not isinstance(data.get("dependencies", {}), dict):
                    errors.append("Config error in package.json: 'dependencies' section must be an object.")
                if not isinstance(data.get("scripts", {}), dict):
                    warnings.append("Config warning in package.json: 'scripts' section is missing or empty.")
            except Exception as e:
                errors.append(f"Config error in '{path}': invalid package.json syntax: {e}")

        # requirements.txt
        elif name == "requirements.txt":
            for idx, line in enumerate(content.splitlines(), 1):
                clean_line = line.strip()
                if not clean_line or clean_line.startswith("#"):
                    continue
                # Simple check: should not contain spaces in module declarations unless it is comment or flag
                if " " in clean_line and not clean_line.startswith("-"):
                    warnings.append(f"Config warning in '{path}': suspicious package requirement line {idx}: '{clean_line}' contains whitespace.")

        # .env.example
        elif name == ".env.example" or name == ".env":
            # Check for secrets accidentally placed in env config
            for idx, line in enumerate(content.splitlines(), 1):
                if "=" in line:
                    parts = line.split("=", 1)
                    val = parts[1].strip().strip("'\"")
                    if val and self._is_actual_secret(val):
                        errors.append(f"CRITICAL: Hardcoded actual secret detected in configuration '{path}' on line {idx}.")

    def _scan_secrets(self, path: str, content: str) -> List[Dict[str, Any]]:
        """Walks content and returns a list of detected actual secrets, keeping value redacted in report."""
        detected = []
        for idx, line in enumerate(content.splitlines(), 1):
            for pattern in SECRET_PATTERNS:
                matches = re.finditer(pattern, line, re.IGNORECASE)
                for m in matches:
                    # If regex contains groups, check group 2 (which is the value)
                    val = m.group(2) if len(m.groups()) >= 2 else m.group(1)
                    if self._is_actual_secret(val):
                        detected.append({
                            "path": path,
                            "line": idx,
                            "pattern": pattern,
                            "value": "[REDACTED]"
                        })
        return detected

    def _is_actual_secret(self, value: str) -> bool:
        """Heuristically audits strings to determine if they are actual hardcoded keys or standard placeholders."""
        clean = value.strip().strip("'\"")
        if not clean or len(clean) < 8:
            return False

        lower_val = clean.lower()
        # If it matches common placeholders, ignore it
        if any(p in lower_val for p in PLACEHOLDERS):
            return False

        # If it is mostly uppercase environment variable like E.G. "DATABASE_URL_HERE", ignore it
        if re.match(r"^[A-Z0-9_]+$", clean):
            return False

        # Standard OpenAI api key shape SK-
        if clean.startswith("sk-") or clean.startswith("AIza"):
            return True

        # Has mixed alphanumeric character distribution (high entropy)
        has_letters = bool(re.search(r"[a-zA-Z]", clean))
        has_digits = bool(re.search(r"[0-9]", clean))
        if has_letters and has_digits:
            return True

        return False

    def _compute_quality_score(self, errors: List[str], warnings: List[str], total_files: int) -> tuple[float, str]:
        """Calculates score 0-100 and maps status: PASS, WARNING, FAIL."""
        if total_files == 0:
            return 0.0, "FAIL"

        score = 100.0

        # Each critical error subtracts 15 points
        criticals = sum(1 for err in errors if "CRITICAL" in err or "Syntax/Structure error" in err or "Config error" in err)
        score -= (criticals * 15)

        # Other errors subtract 8 points
        other_errors = len(errors) - criticals
        score -= (other_errors * 8)

        # Each warning subtracts 3 points
        score -= (len(warnings) * 3)

        score = max(0.0, min(100.0, score))

        if score < 70.0 or len(errors) > 0:
            status = "FAIL"
        elif len(warnings) > 0:
            status = "WARNING"
        else:
            status = "PASS"

        return float(round(score, 1)), status


# Global ProjectValidator Instance
global_project_validator = ProjectValidator()
