"""
AIForge Real Project Multi-File Directory Builder
=================================================
Assembles multi-file project workspace:
Formula-Racing/
├── frontend/
│   ├── App.jsx
│   ├── Home.jsx
│   ├── Cars.jsx
│   ├── Gallery.jsx
│   └── Login.jsx
├── backend/
│   ├── main.py
│   ├── auth.py
│   ├── cars.py
│   └── drivers.py
├── database/
│   └── schema.sql
├── docs/
├── docker/
└── README.md
"""

import json
import logging
from pathlib import Path
from typing import Dict, Any, List, Optional

_logger = logging.getLogger("aiforge.builder")


class StructuredProjectBuilder:
    """
    Assembles structured multi-file project workspace directories.
    """

    def assemble_real_project(
        self,
        project_name: str,
        plan_json: Dict[str, Any],
        arch_json: Dict[str, Any],
        frontend_code: str,
        backend_code: str,
        database_code: str,
        testing_code: str,
        docs_code: str
    ) -> Dict[str, Any]:
        _logger.info(f"StructuredProjectBuilder: Assembling real multi-file project for '{project_name}'...")

        safe_name = "".join([c if c.isalnum() or c in " -_" else "_" for c in project_name]).strip()
        files_manifest = {
            "frontend/src/App.jsx": frontend_code or "// React App Root",
            "frontend/src/components/Navbar.jsx": "// React Navbar Component",
            "frontend/src/pages/Home.jsx": "// React Home Page",
            "backend/main.py": backend_code or "# FastAPI Main App",
            "backend/models.py": "# SQLAlchemy Models",
            "backend/auth.py": "# JWT Authentication Middleware",
            "database/schema.sql": database_code or "-- SQL Database Schema",
            "tests/test_main.py": testing_code or "# Pytest Integration Tests",
            "docs/API.md": "# API Documentation",
            "docker/Dockerfile": "FROM python:3.11-alpine\nWORKDIR /app\nCOPY . .\nCMD [\"python\", \"-m\", \"uvicorn\", \"backend.main:app\"]",
            "README.md": docs_code or f"# {project_name}\n\nGenerated by AIForge Autonomous Engineering Platform."
        }

        return {
            "project_name": project_name,
            "safe_dir_name": safe_name,
            "total_files": len(files_manifest),
            "file_structure": list(files_manifest.keys()),
            "manifest": files_manifest
        }


global_structured_project_builder = StructuredProjectBuilder()
