import json
import logging
import asyncio
from time import perf_counter

from fastapi import APIRouter
from fastapi.responses import StreamingResponse
from pydantic import BaseModel

from backend.graph.project_workflow import project_graph
from backend.services.llm import stream_queue_var

router = APIRouter()
logger = logging.getLogger("aiforge.performance")


class ProjectRequest(BaseModel):
    prompt: str


# Progress percentages reported as each stage completes.
PROGRESS_STEPS = {
    "planner": 10,
    "architect": 20,
    "frontend": 35,
    "backend": 50,
    "database": 65,
    "reviewer": 80,
    "testing": 90,
    "documentation": 99,
    "completed": 100,
}


def _full_result(state: dict) -> dict:
    return {
        "plan": state.get("plan", ""),
        "architecture": state.get("architecture", ""),
        "frontend": state.get("frontend", ""),
        "backend": state.get("backend", ""),
        "database": state.get("database", ""),
        "documentation": state.get("documentation", ""),
        "tests": state.get("tests", ""),
        "review": state.get("review", ""),
        "github": state.get("github", ""),
        "error": state.get("error", ""),
    }


@router.post("/generate-project")
async def generate_project(request: ProjectRequest):
    """
    Runs the full autonomous project-generation pipeline and returns the
    complete result in a single response.
    """

    pipeline_started_at = perf_counter()

    result = await project_graph.ainvoke({"user_prompt": request.prompt})

    total_elapsed_ms = (perf_counter() - pipeline_started_at) * 1000
    print(f"Total Pipeline Time: {total_elapsed_ms:.1f}ms")
    logger.info("Total Pipeline Time: %.1fms", total_elapsed_ms)

    return _full_result(result)


@router.post("/generate-project/stream")
async def generate_project_stream(request: ProjectRequest):
    """
    Streams progress events (Server-Sent Events) while the pipeline runs,
    so the UI can show live progress instead of appearing frozen.
    Streams incremental token chunks as they are generated by the LLM,
    along with stage-completed output events.
    """

    async def event_stream():
        pipeline_started_at = perf_counter()

        # Set up streaming queue in contextvars
        queue = asyncio.Queue()
        token = stream_queue_var.set(queue)

        # Execute the project generation graph in a background task
        graph_task = asyncio.create_task(
            project_graph.ainvoke({"user_prompt": request.prompt})
        )

        final_state = {"user_prompt": request.prompt}

        # Consume events from the queue until the graph finishes and queue is drained
        while not graph_task.done() or not queue.empty():
            try:
                # Wait briefly for queue elements so we don't block forever and can check graph_task status
                item = await asyncio.wait_for(queue.get(), timeout=0.1)
                event_type, stage, data = item

                if event_type == "chunk":
                    payload = {
                        "stage": stage,
                        "percent": PROGRESS_STEPS.get(stage, 0),
                        "chunk": data,
                    }
                    yield f"data: {json.dumps(payload)}\n\n"
                elif event_type == "completed":
                    final_state.update(data)
                    payload = {
                        "stage": stage,
                        "percent": PROGRESS_STEPS.get(stage, 0),
                        "output": data,
                    }
                    yield f"data: {json.dumps(payload)}\n\n"

                queue.task_done()
            except asyncio.TimeoutError:
                continue
            except Exception as exc:  # noqa: BLE001
                error_payload = {"stage": "error", "percent": 0, "output": {"error": str(exc)}}
                yield f"data: {json.dumps(error_payload)}\n\n"
                stream_queue_var.reset(token)
                return

        # Double check if any exception occurred in the task itself
        try:
            result = await graph_task
            final_state.update(result)
        except Exception as exc:  # noqa: BLE001
            error_payload = {"stage": "error", "percent": 0, "output": {"error": str(exc)}}
            yield f"data: {json.dumps(error_payload)}\n\n"
            stream_queue_var.reset(token)
            return

        total_elapsed_ms = (perf_counter() - pipeline_started_at) * 1000
        print(f"Total Pipeline Time: {total_elapsed_ms:.1f}ms")
        logger.info("Total Pipeline Time: %.1fms", total_elapsed_ms)

        completed_payload = {
            "stage": "completed",
            "percent": 100,
            "output": _full_result(final_state),
        }
        yield f"data: {json.dumps(completed_payload)}\n\n"

        # Reset context variable to prevent memory leak
        stream_queue_var.reset(token)

    return StreamingResponse(event_stream(), media_type="text/event-stream")


