OLLAMA_SMALL_MODEL = "qwen2.5-coder:latest"
OLLAMA_MEDIUM_MODEL = "qwen2.5:latest"
OLLAMA_LARGE_MODEL = "qwen2.5:latest"

DEFAULT_OLLAMA_MODEL = OLLAMA_SMALL_MODEL

MAX_HISTORY_MESSAGES = 5
CONVERSATION_HISTORY_TURNS = 10
MAX_PROMPT_CHARS = 12000
MAX_CACHE_ITEMS = 128