"""
Unit and Integration Tests for AIForge ArchitectAgent & ArchitectureSpec
"""

import pytest
from unittest.mock import AsyncMock
from backend.agents.architect_agent import ArchitectAgent
from backend.schemas.agent_contract import ArchitectureSpec, ProjectSpec
from backend.graph.project_state import ProjectState
from backend.graph.project_workflow import architect_node


def test_architect_valid_json_parsing():
    agent = ArchitectAgent()
    raw_output = """
```json
{
  "project_name": "TodoApp",
  "architecture_style": "Modular Monolith",
  "frontend": "React",
  "backend": "FastAPI",
  "database": "PostgreSQL",
  "components": ["Navbar", "TodoList", "TodoItem", "LoginForm"],
  "routes": ["GET /api/todos", "POST /api/todos", "POST /api/auth/login"],
  "models": ["User", "Todo"],
  "dependencies": ["react", "fastapi", "sqlalchemy", "pydantic"],
  "folder_structure": {
    "frontend": ["src/App.jsx", "src/components/TodoList.jsx"],
    "backend": ["main.py", "models.py"]
  }
}
```
"""
    arch = agent.parse_architecture_json(raw_output, allow_fallback=False)

    assert arch["project_name"] == "TodoApp"
    assert arch["architecture_style"] == "Modular Monolith"
    assert len(arch["components"]) == 4
    assert len(arch["routes"]) == 3
    assert len(arch["models"]) == 2
    assert "react" in arch["dependencies"]


def test_architect_missing_optional_fields():
    agent = ArchitectAgent()
    raw_output = '```json\n{"project_name": "SimpleApp"}\n```'
    arch = agent.parse_architecture_json(raw_output, allow_fallback=True)

    assert arch["project_name"] == "SimpleApp"
    assert arch["architecture_style"] == "Modular Monolith"
    assert arch["frontend"] == "React"
    assert arch["backend"] == "FastAPI"
    assert arch["database"] == "PostgreSQL"
    assert isinstance(arch["components"], list)
    assert isinstance(arch["routes"], list)
    assert isinstance(arch["models"], list)


def test_architect_malformed_json_raises_error():
    agent = ArchitectAgent()
    raw_output = "Broken output without valid JSON { 'project': 'Invalid"
    with pytest.raises(ValueError, match="Architect output"):
        agent.parse_architecture_json(raw_output, allow_fallback=False)


def test_architect_backward_compatibility():
    agent = ArchitectAgent()
    raw_output = '```json\n{"components": ["App"], "routes": ["GET /health"], "models": ["User"]}\n```'
    arch = agent.parse_architecture_json(raw_output, allow_fallback=True)

    # Downstream consumers (validator, frontend, backend, database) check these keys
    required_keys = ["components", "routes", "models", "dependencies", "folder_structure"]
    for key in required_keys:
        assert key in arch


@pytest.mark.anyio
async def test_planner_to_architect_integration():
    from backend.graph import project_workflow

    # Mock LLM output for ArchitectAgent
    mock_arch_json = """
```json
{
  "project_name": "TodoManager",
  "architecture_style": "Modular Monolith",
  "frontend": "React",
  "backend": "FastAPI",
  "database": "PostgreSQL",
  "components": ["TodoList", "TodoItem", "AuthForm"],
  "routes": ["GET /api/todos", "POST /api/todos", "POST /api/auth/token"],
  "models": ["User", "Todo"],
  "dependencies": ["react", "fastapi", "sqlalchemy", "pydantic"]
}
```
"""
    project_workflow.architect.run_async = AsyncMock(return_value=mock_arch_json)

    # Realistic ProjectSpec generated by Planner
    spec = ProjectSpec(
        project_name="TodoManager",
        domain="Productivity",
        type="Full Stack Web App",
        functional_requirements=["FR-1: User Login", "FR-2: CRUD Todos"],
        frontend="React",
        backend="FastAPI",
        database="PostgreSQL"
    )

    state: ProjectState = {
        "prompt": "Build a Todo application with authentication, CRUD, React, FastAPI, PostgreSQL",
        "project_name": "TodoManager",
        "project_spec": spec.model_dump(),
        "plan": spec.model_dump()
    }

    state_update = await architect_node(state)

    assert "architecture" in state_update
    arch = state_update["architecture"]

    assert arch["project_name"] == "TodoManager"
    assert arch["frontend"] == "React"
    assert arch["backend"] == "FastAPI"
    assert arch["database"] == "PostgreSQL"
    assert "TodoList" in arch["components"]
    assert "GET /api/todos" in arch["routes"]
    assert "User" in arch["models"]
