"""
AIForge Multi-LLM Execution Manager & Failover Engine
=====================================================
Handles execution, parallel multi-model dispatch, and automatic failover retries (Qwen -> DeepSeek -> GPT -> Claude).
"""

import time
import asyncio
import logging
from typing import Dict, Any, List
from backend.llm.model_registry import MODELS
from backend.llm.response_evaluator import ResponseEvaluator

_logger = logging.getLogger("aiforge.llm")

class ModelManager:
    """
    Manages execution across local and cloud LLM providers, including automatic failover retries.
    """

    def __init__(self, evaluator: ResponseEvaluator = None) -> None:
        if evaluator is None:
            evaluator = ResponseEvaluator()
        self.evaluator = evaluator

    async def _execute_single_model(self, model_key: str, prompt: str) -> Dict[str, Any]:
        """
        Simulates model execution for local (Ollama) or cloud providers.
        """
        start_time = time.perf_counter()
        model_info = MODELS.get(model_key, MODELS["qwen"])

        # Failover simulation hook for testing
        if model_info.get("force_fail", False):
            raise TimeoutError(f"Model '{model_key}' connection timed out.")

        # Simulate execution output
        await asyncio.sleep(0.05) # Simulated generation latency
        latency = (time.perf_counter() - start_time)

        response_text = f"// Generated by {model_info['name']} ({model_key})\n# Output for: {prompt}\n\ndef main():\n    return {{'status': 200, 'model': '{model_key}'}}"

        return {
            "model_key": model_key,
            "model_name": model_info["name"],
            "type": model_info["type"],
            "latency": latency,
            "response": response_text
        }

    async def execute_with_failover(self, primary_model_key: str, prompt: str) -> Dict[str, Any]:
        """
        Executes primary model with fallback chain: Qwen -> DeepSeek -> GPT -> Claude.
        """
        fallback_chain = ["qwen", "deepseek", "gpt", "claude"]
        if primary_model_key in fallback_chain:
            fallback_chain.remove(primary_model_key)
        fallback_chain.insert(0, primary_model_key)

        retries = 0
        last_exception = None

        for model_key in fallback_chain:
            try:
                _logger.info(f"Attempting execution with model '{model_key}'...")
                res = await self._execute_single_model(model_key, prompt)
                res["retries_count"] = retries
                return res
            except Exception as e:
                _logger.warning(f"Model '{model_key}' failed: {e}. Triggering failover to next model...")
                retries += 1
                last_exception = e

        raise RuntimeError(f"All models in failover chain failed. Last error: {last_exception}")

    async def execute_parallel(self, prompt: str, model_keys: List[str] = None) -> Dict[str, Any]:
        """
        Executes multiple models concurrently and selects top winner via AI Judge.
        """
        if model_keys is None:
            model_keys = ["qwen", "deepseek", "gpt"]

        tasks = [self._execute_single_model(mk, prompt) for mk in model_keys if mk in MODELS]
        results = await asyncio.gather(*tasks, return_exceptions=True)

        valid_results = [r for r in results if isinstance(r, dict)]
        if not valid_results:
            raise RuntimeError("Parallel model execution produced 0 valid outputs.")

        evaluation = self.evaluator.select_best_response(valid_results)
        return {
            "strategy": "parallel",
            "evaluated_count": len(valid_results),
            "winner": evaluation["winner_model"],
            "winning_response": evaluation["winning_response"],
            "winner_score": evaluation["winner_score"],
            "all_results": valid_results
        }
