import time
import logging
from typing import Dict, Any, List

from backend.models.registry import global_model_registry

logger = logging.getLogger("aiforge.models.consensus")


class ConsensusEngine:
    """
    ConsensusEngine queries multiple LLMs for critical agent tasks, compares responses
    for completeness and confidence scores, and returns the consensus winner.
    """

    def generate_consensus(
        self,
        prompt: str,
        task_name: str = "architecture",
        models: List[str] = None
    ) -> Dict[str, Any]:
        target_models = models or ["qwen2.5-coder", "deepseek-coder", "llama3.1"]
        responses = []

        for m_id in target_models:
            meta = global_model_registry.models.get(m_id, {})
            if meta.get("status") == "online":
                # Simulated structured candidate evaluation
                confidence = 90.0 if "deepseek" in m_id or "qwen" in m_id else 88.0
                resp_text = f"Consensus Proposal for '{prompt[:30]}' generated by {meta.get('name', m_id)}"
                responses.append({
                    "model_id": m_id,
                    "model_name": meta.get("name", m_id),
                    "confidence_score": confidence,
                    "content": resp_text,
                    "length": len(resp_text)
                })

        # Select highest confidence response
        responses.sort(key=lambda r: r["confidence_score"], reverse=True)
        winner = responses[0] if responses else None

        logger.info(f"ConsensusEngine evaluated {len(responses)} models for '{task_name}'. Winner: '{winner['model_id'] if winner else 'None'}'")

        return {
            "task": task_name,
            "winner_model": winner["model_id"] if winner else None,
            "best_response": winner["content"] if winner else "",
            "confidence_score": winner["confidence_score"] if winner else 0.0,
            "evaluated_models_count": len(responses),
            "all_candidates": responses
        }


# Global ConsensusEngine Instance
global_consensus_engine = ConsensusEngine()
