"""
AIForge Autonomous AI Software Engineer Engine - Structured Agent Contracts
=============================================================================
Defines Pydantic structured JSON schemas for universal agent context delivery and structured agent output.
Agents communicate strictly using these structured models.
"""

from typing import Dict, Any, List, Optional
from pydantic import BaseModel, Field


class FileArtifact(BaseModel):
    path: str = Field(..., description="Relative file path, e.g., 'src/components/Navbar.jsx' or 'backend/app/main.py'")
    purpose: str = Field(..., description="Technical purpose of the file")
    content: str = Field(..., description="Full production-ready file content without placeholders")
    dependencies: List[str] = Field(default_factory=list, description="Imports or packages required by this file")
    language: str = Field(default="python", description="File programming language")


class APIContractItem(BaseModel):
    endpoint: str = Field(..., description="API route endpoint, e.g., '/api/auth/login'")
    method: str = Field(..., description="HTTP Method (GET, POST, PUT, DELETE)")
    summary: str = Field(..., description="Endpoint description")
    request_schema: Dict[str, Any] = Field(default_factory=dict)
    response_schema: Dict[str, Any] = Field(default_factory=dict)


class DatabaseEntity(BaseModel):
    table_name: str = Field(..., description="SQL table name")
    columns: List[Dict[str, str]] = Field(default_factory=list, description="Column definitions: name, type, constraints")
    relationships: List[str] = Field(default_factory=list, description="Foreign keys and relationships")


class AgentContextPayload(BaseModel):
    """
    Universal Context Payload delivered to every specialized agent before code generation.
    """
    project_goal: str = Field(..., description="High-level project objective")
    architecture: Dict[str, Any] = Field(default_factory=dict, description="Software architecture design")
    folder_structure: Dict[str, Any] = Field(default_factory=dict, description="Project directory layout")
    technology_stack: Dict[str, str] = Field(default_factory=dict, description="Frontend, backend, DB, and devops stack")
    coding_standards: List[str] = Field(default_factory=list, description="Coding guidelines and best practices")
    already_generated_files: Dict[str, str] = Field(default_factory=dict, description="Persistent project memory files")
    dependencies: Dict[str, List[str]] = Field(default_factory=dict, description="Frontend and backend packages")
    database_schema: str = Field(default="", description="PostgreSQL 3NF SQL schema string")
    api_contracts: List[APIContractItem] = Field(default_factory=list, description="REST API endpoint definitions")
    component_relationships: List[str] = Field(default_factory=list, description="UI component hierarchy")
    task_description: str = Field(..., description="Atomic task assignment for this agent")
    expected_output: str = Field(..., description="Target deliverable description")
    acceptance_criteria: List[str] = Field(default_factory=list, description="Quality checklist items")


class StructuredAgentOutput(BaseModel):
    """
    Structured JSON output generated by every specialized agent.
    """
    project_name: str = Field(..., description="Project name")
    task: str = Field(..., description="Agent task identifier")
    agent_name: str = Field(..., description="Name of the agent, e.g., 'FrontendAgent'")
    files: List[FileArtifact] = Field(default_factory=list, description="Generated file artifacts")
    api: List[APIContractItem] = Field(default_factory=list, description="API contracts defined or used")
    database: List[DatabaseEntity] = Field(default_factory=list, description="Database entities defined or used")
    notes: List[str] = Field(default_factory=list, description="Architecture notes and decisions")
    quality_score: float = Field(default=95.0, description="Self-evaluated quality score out of 100")


class ProjectSpec(BaseModel):
    """
    Structured Project Specification contract generated by PlannerAgent.
    """
    project_name: str = Field(default="AIForge Application", description="Name of the software project")
    domain: str = Field(default="Software Product", description="Product category or domain")
    type: str = Field(default="Full Stack Web App", description="Application architecture type")
    executive_summary: str = Field(default="", description="High-level product summary")
    requirements: List[str] = Field(default_factory=list, description="All requirements")
    functional_requirements: List[str] = Field(default_factory=list, description="Detailed functional requirements (FR-1, FR-2, ...)")
    non_functional_requirements: List[str] = Field(default_factory=list, description="NFR performance, security, availability targets")
    user_stories: List[str] = Field(default_factory=list, description="User story list")
    assumptions: List[str] = Field(default_factory=list, description="Explicit assumptions")
    constraints: List[str] = Field(default_factory=list, description="Technical and business constraints")
    pages: List[str] = Field(default_factory=list, description="Key UI pages/screens")
    features: List[str] = Field(default_factory=list, description="Core feature checklist")
    frontend: str = Field(default="React", description="Selected frontend framework")
    backend: str = Field(default="FastAPI", description="Selected backend framework")
    database: str = Field(default="PostgreSQL", description="Selected database engine")
    dependencies: List[str] = Field(default_factory=list, description="Key software dependencies")
    api_requirements: List[str] = Field(default_factory=list, description="Target REST API requirement endpoints")
    important_constraints: List[str] = Field(default_factory=list, description="Critical architectural constraints")
    tech_stack: Dict[str, str] = Field(default_factory=dict, description="Recommended technology stack components")


class ArchitectureSpec(BaseModel):
    """
    Structured Architecture Specification contract generated by ArchitectAgent.
    """
    project_name: str = Field(default="AIForge Application", description="Name of the project")
    architecture_style: str = Field(default="Modular Monolith", description="Architecture pattern style")
    frontend: str = Field(default="React", description="Selected frontend framework")
    backend: str = Field(default="FastAPI", description="Selected backend framework")
    database: str = Field(default="PostgreSQL", description="Selected database engine")
    components: List[str] = Field(default_factory=list, description="UI components and modules")
    routes: List[str] = Field(default_factory=list, description="API endpoints and routes")
    models: List[str] = Field(default_factory=list, description="Database entities and models")
    dependencies: List[str] = Field(default_factory=list, description="Third-party packages and libraries")
    folder_structure: Dict[str, Any] = Field(default_factory=dict, description="Project directory tree")
    auth_strategy: str = Field(default="JWT Bearer Authentication", description="Authentication mechanism")
    environment_variables: List[str] = Field(default_factory=list, description="Required environment variables")
    architectural_decisions: List[str] = Field(default_factory=list, description="Key architecture decisions")



