"""
AIForge Closed-Loop Execution & Self-Healing Workflow
=====================================================
Executes real sandbox build/test checks on assembled disk artifacts,
enforces deliverable validation, and performs bounded self-healing retries
using actual build stdout/stderr outputs.
"""

import os
import shutil
import logging
from pathlib import Path
from typing import Dict, Any, List

from backend.orchestrator.deterministic_router import global_deterministic_router
from backend.services.project_builder import global_structured_project_builder
from backend.services.validator import global_stage_validator
from backend.execution.sandbox_executor import global_sandbox_executor
from backend.execution.models import CodeArtifact, ExecutionType
from backend.agents.planner_agent import PlannerAgent
from backend.agents.architect_agent import ArchitectAgent
from backend.agents.frontend_agent import FrontendAgent
from backend.agents.backend_agent import BackendAgent
from backend.agents.database_agent import DatabaseAgent
from backend.agents.reviewer_agent import ReviewerAgent
from backend.agents.debug_agent import DebugAgent

_logger = logging.getLogger("aiforge.execution_loop")

class ExecutionHealingLoop:
    def __init__(self, max_retries: int = 3):
        self.max_retries = max_retries
        self.planner = PlannerAgent()
        self.architect = ArchitectAgent()
        self.frontend_agent = FrontendAgent()
        self.backend_agent = BackendAgent()
        self.database_agent = DatabaseAgent()
        self.reviewer = ReviewerAgent()
        self.debugger = DebugAgent()

    async def run_autonomous_workflow(self, prompt: str, session_id: str = "default") -> Dict[str, Any]:
        logs: List[str] = []
        _logger.info(f"Starting Closed-Loop Execution Workflow for session: {session_id}")
        logs.append("✔ Step 1/6: Deterministic Requirement Routing (0ms)")

        # 1. Deterministic Routing (No LLM latency)
        route_meta = global_deterministic_router.analyze_prompt(prompt)
        proj_name = route_meta["project_name"]
        logs.append(f"  └ Target Stack: {route_meta['frontend']} + {route_meta['backend']} + {route_meta['database']}")

        # 2. Planning & Architecture
        logs.append("✔ Step 2/6: Planning & Architecture Generation")
        plan_raw = await self.planner.run_async(prompt)
        _, _, plan_json = global_stage_validator.validate_plan(plan_raw)
        plan_json["project_name"] = proj_name

        arch_raw = await self.architect.run_async(f"Architecture for {proj_name}: {prompt}")
        _, _, arch_json = global_stage_validator.validate_architecture(arch_raw)

        # 3. Parallel Code Generation
        logs.append("✔ Step 3/6: Parallel Component Code Generation (Frontend, Backend, Database)")
        fe_code = await self.frontend_agent.run_async(f"Frontend App for {proj_name}")
        be_code = await self.backend_agent.run_async(f"Backend API for {proj_name}")
        db_code = await self.database_agent.run_async(f"Database Schema for {proj_name}")

        # 4. Assembled Disk Workspace
        logs.append("✔ Step 4/6: Disk Workspace Assembly")
        repo_root = Path(__file__).resolve().parent.parent.parent
        workspace_dir = repo_root / "workspace" / f"sandbox_{session_id}"
        if workspace_dir.exists():
            shutil.rmtree(workspace_dir, ignore_errors=True)
        workspace_dir.mkdir(parents=True, exist_ok=True)

        assembled = global_structured_project_builder.assemble_real_project(
            project_name=proj_name,
            plan_json=plan_json,
            arch_json=arch_json,
            frontend_code=fe_code,
            backend_code=be_code,
            database_code=db_code,
            testing_code="",
            docs_code=f"# {proj_name}\nAutogenerated by AIForge."
        )

        manifest = assembled.get("manifest", {})
        for relative_path, file_content in manifest.items():
            out_file = workspace_dir / relative_path
            out_file.parent.mkdir(parents=True, exist_ok=True)
            out_file.write_text(file_content, encoding="utf-8")

        logs.append(f"  └ Assembled {len(manifest)} files into workspace/{workspace_dir.name}")

        # 5. Execution Grounding & Self-Healing Loop
        logs.append("✔ Step 5/6: Execution Grounding (Build & Test Sandbox)")
        attempt = 0
        is_success = False
        execution_report = {}

        main_py = workspace_dir / "backend" / "main.py"
        if not main_py.exists():
            main_py = workspace_dir / "main.py"

        while attempt < self.max_retries and not is_success:
            attempt += 1
            logs.append(f"  ├ Sandbox Verification Run (Attempt {attempt}/{self.max_retries})...")

            # Validate Deliverable Files & Syntax
            val_res = global_stage_validator.validate_final_deliverable(workspace_dir)

            # Sandbox Code Execution
            artifacts = []
            if main_py.exists():
                artifacts.append(CodeArtifact(filename=main_py.name, content=main_py.read_text(encoding="utf-8"), purpose="SOURCE"))

            exec_res = global_sandbox_executor.execute(
                artifacts=artifacts,
                language="python",
                execution_type=ExecutionType.TEST
            )

            build_passed = val_res["is_valid"] and exec_res.exit_code == 0
            if build_passed:
                is_success = True
                logs.append("  └ Sandbox Execution & Build PASSED with 0 errors!")
                execution_report = {
                    "attempt": attempt,
                    "status": "PASS",
                    "deliverable_validation": val_res,
                    "stdout": exec_res.stdout,
                    "stderr": exec_res.stderr
                }
            else:
                stderr_output = exec_res.stderr or "; ".join(val_res.get("errors", ["Build error"]))
                logs.append(f"  ⚠️ Sandbox Execution Failed: {stderr_output[:120]}...")

                if attempt < self.max_retries:
                    logs.append("  └ Invoking Self-Healing Debugger Agent with actual stderr...")
                    error_context = f"Attempt {attempt} build/test failure.\nErrors:\n{stderr_output}\nSource File:\n{main_py.read_text(encoding='utf-8') if main_py.exists() else be_code}"
                    patch_suggestion = await self.debugger.run_async(error_context)
                    if main_py.exists() and "def " in patch_suggestion:
                        main_py.write_text(patch_suggestion, encoding="utf-8")
                        be_code = patch_suggestion

        # 6. Structured Code Review
        logs.append("✔ Step 6/6: Structured Reviewer Gate")
        review_raw = await self.reviewer.run_async(f"Review {proj_name}", previous_output=f"Backend:\n{be_code}\nFrontend:\n{fe_code}")
        review_json = self.reviewer.parse_review_json(review_raw)
        logs.append(f"  └ Reviewer Status: {review_json.get('status', 'PASS')} (Score: {review_json.get('score', 85)})")

        final_status = "SUCCESS" if is_success and review_json.get("status") == "PASS" else "COMPLETED_WITH_WARNINGS"

        return {
            "status": final_status,
            "project_name": proj_name,
            "session_id": session_id,
            "workspace_path": str(workspace_dir),
            "manifest": manifest,
            "routing": route_meta,
            "execution_report": execution_report,
            "review": review_json,
            "logs": logs
        }

global_execution_healing_loop = ExecutionHealingLoop()
