import logging
from typing import Dict, Any

logger = logging.getLogger("aiforge.exporter.readme_generator")


class ReadmeGenerator:
    """
    ReadmeGenerator constructs a comprehensive, production-ready README.md
    documentation file dynamically from workflow state and project metadata.
    """

    def generate_readme(self, project_name: str, prompt: str, tech_stack: Dict[str, Any], routes: List[str] = None) -> str:
        fe = tech_stack.get("frontend", "React (Vite + Tailwind CSS)")
        be = tech_stack.get("backend", "FastAPI (Python 3.11)")
        db = tech_stack.get("database", "PostgreSQL 16")
        auth = tech_stack.get("auth", "JWT Tokens")

        routes_str = "\n".join([f"- `{r}`" for r in (routes or ["GET /health", "GET /api/tasks", "POST /api/auth/login"])])

        readme_content = f"""# 🚀 {project_name}

> Generated by **AIForge V2 Autonomous Platform Engine**

## 📖 Overview
{prompt}

---

## ✨ Features & Architecture
- **Authentication**: {auth}
- **Frontend SPA**: {fe}
- **Backend REST API**: {be}
- **Database Engine**: {db}
- **Automated Tests**: Pytest & React Testing Library

---

## 🛠️ Tech Stack
- **Frontend**: React 18, Vite, Tailwind CSS, Axios, React Icons
- **Backend**: FastAPI, Uvicorn ASGI, Pydantic V2, SQLAlchemy ORM
- **Database**: PostgreSQL / SQLite schema
- **DevOps**: Docker, Docker Compose, GitHub Actions CI/CD

---

## 🚦 Quick Start Guide

### 1. Backend Setup
```bash
cd backend
python -m venv .venv
source .venv/bin/activate  # On Windows: .venv\\Scripts\\activate
pip install -r requirements.txt
uvicorn main:app --reload --port 8000
```
Backend API server will run at: `http://127.0.0.1:8000`

### 2. Frontend Setup
```bash
cd frontend
npm install
npm run dev
```
Frontend Web App will run at: `http://localhost:5173`

---

## 🔑 Environment Variables (.env.example)
```env
DATABASE_URL=postgresql://postgres:postgres@localhost:5432/app_db
JWT_SECRET=super_secret_jwt_key_aiforge_v2
SECRET_KEY=production_secret_key
PORT=8000
```

---

## 🔌 API Endpoints
{routes_str}

---

## 📂 Folder Structure
```text
project/
├── frontend/
│   ├── src/
│   │   ├── components/
│   │   └── App.jsx
│   └── package.json
├── backend/
│   ├── main.py
│   └── requirements.txt
├── database/
│   └── schema.sql
├── tests/
│   └── test_api.py
├── .env.example
├── docker-compose.yml
└── README.md
```
"""
        return readme_content


# Global ReadmeGenerator Instance
global_readme_generator = ReadmeGenerator()
