"""
AIForge Intelligent Self-Review & Reflection Models
===================================================
Typed schemas for Review Decisions, Critique Issues, Critique Results,
and Refinement Results.
"""

from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field


class ReviewDecision(BaseModel):
    """
    Typed decision returned by ReviewPolicy indicating whether self-review is justified.
    """
    should_review: bool = Field(description="True if self-review should be executed")
    reason: str = Field(description="Short categorical label explaining review decision")
    priority: str = Field(default="medium", description="Priority: 'high', 'medium', 'low', 'none'")


class CritiqueIssue(BaseModel):
    """
    Structured issue identified by ResponseCritic.
    """
    category: str = Field(description="Issue category (REQUIREMENT_MISSING, SECURITY, CORRECTNESS, etc.)")
    severity: str = Field(description="Severity: 'high', 'medium', 'low'")
    description: str = Field(description="Concise description of the identified defect")
    suggested_action: str = Field(description="Actionable guidance to address the issue")


class CritiqueResult(BaseModel):
    """
    Typed critique result generated by ResponseCritic.
    Private chain-of-thought traces are never exposed to the user.
    """
    needs_revision: bool = Field(default=False, description="True if response requires material refinement")
    score: float = Field(default=1.0, description="Response quality score assigned by critic (0.0 to 1.0)")
    issues: List[CritiqueIssue] = Field(default_factory=list, description="List of concrete identified issues")
    strengths: List[str] = Field(default_factory=list, description="Key strengths of the initial response")
    missing_requirements: List[str] = Field(default_factory=list, description="Explicit user requirements missing from response")
    priority: str = Field(default="low", description="Refinement priority: 'high', 'medium', 'low'")
    is_valid: bool = Field(default=True, description="True if critique output is valid and well-formed")


class RefinementResult(BaseModel):
    """
    Typed result returned by RefinementController.
    """
    refined_response: str = Field(description="Refined response text")
    attempts: int = Field(default=1, description="Refinement attempt count")
    validation_passed: bool = Field(default=True, description="True if refined response passed OutputValidator")
    quality_score: float = Field(default=100.0, description="Quality score of refined response")
    improvement_made: bool = Field(default=False, description="True if refinement measurably improved response")
