import logging
from pathlib import Path
from datetime import datetime

_logger = logging.getLogger("aiforge.performance")


class ReportGenerator:
    """
    Generates a structured, professional Markdown quality report summarizing
    architecture compliance, security scans, performance audits, and testing metrics.
    """

    def __init__(self) -> None:
        pass

    def generate_report_content(
        self,
        project_name: str,
        findings: list[dict],
        test_results: dict,
        scores: dict
    ) -> str:
        """
        Builds the Markdown content for the report.
        """
        _logger.info("Generating reports/project_review.md content...")

        # Separate findings into critical, warning, info
        criticals = [f for f in findings if f.get("severity") == "critical"]
        warnings = [f for f in findings if f.get("severity") == "warning"]
        infos = [f for f in findings if f.get("severity") == "info"]

        # Collect unique files reviewed
        files_reviewed = sorted(list(set(f.get("file", "unknown") for f in findings if f.get("file"))))
        if not files_reviewed:
            files_reviewed = ["No source files identified with quality findings."]

        # Format files reviewed section
        files_str = "\n".join([f"- `{file}`" for file in files_reviewed])

        # Format issues list
        criticals_str = "\n".join([
            f"- **File:** `{f['file']}` (Line {f['line']})\n  - **Issue:** {f['issue']}\n  - **Recommendation:** {f['recommendation']}"
            for f in criticals
        ]) or "_No critical issues detected._"

        warnings_str = "\n".join([
            f"- **File:** `{f['file']}` (Line {f['line']})\n  - **Issue:** {f['issue']}\n  - **Recommendation:** {f['recommendation']}"
            for f in warnings
        ]) or "_No warnings detected._"

        infos_str = "\n".join([
            f"- **File:** `{f['file']}` (Line {f['line']})\n  - **Issue:** {f['issue']}\n  - **Recommendation:** {f['recommendation']}"
            for f in infos
        ]) or "_No info items detected._"

        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        report = f"""# AIForge Project Quality & Review Report

**Project:** {project_name}  
**Date:** {timestamp}  
**Generated By:** 🚀 AIForge Quality & Review Engine  

---

## 📊 Executive Summary

This report outlines the structural checks, static analysis, security vulnerabilities, performance scans, and testing metrics of the compiled project.

### 🏆 Quality Scorecard

| Category | Score / 10.0 | Rating |
| :--- | :---: | :---: |
| **Architecture** | `{scores.get('architecture', 10.0)}` | {'🔴 Critical' if scores.get('architecture', 10.0) < 6.0 else '🟡 Warning' if scores.get('architecture', 10.0) < 8.0 else '🟢 Good'} |
| **Security** | `{scores.get('security', 10.0)}` | {'🔴 Critical' if scores.get('security', 10.0) < 6.0 else '🟡 Warning' if scores.get('security', 10.0) < 8.0 else '🟢 Good'} |
| **Performance** | `{scores.get('performance', 10.0)}` | {'🔴 Critical' if scores.get('performance', 10.0) < 6.0 else '🟡 Warning' if scores.get('performance', 10.0) < 8.0 else '🟢 Good'} |
| **Maintainability** | `{scores.get('maintainability', 10.0)}` | {'🔴 Critical' if scores.get('maintainability', 10.0) < 6.0 else '🟡 Warning' if scores.get('maintainability', 10.0) < 8.0 else '🟢 Good'} |
| **Testing** | `{scores.get('testing', 10.0)}` | {'🔴 Critical' if scores.get('testing', 10.0) < 6.0 else '🟡 Warning' if scores.get('testing', 10.0) < 8.0 else '🟢 Good'} |
| **Documentation** | `{scores.get('documentation', 10.0)}` | {'🔴 Critical' if scores.get('documentation', 10.0) < 6.0 else '🟡 Warning' if scores.get('documentation', 10.0) < 8.0 else '🟢 Good'} |
| **OVERALL** | **`{scores.get('overall', 10.0)}`** | **{'🔴 Critical' if scores.get('overall', 10.0) < 6.0 else '🟡 Warning' if scores.get('overall', 10.0) < 8.0 else '🟢 Good'}** |

---

## 🧪 Testing Results

- **Passed Tests:** `{test_results.get('passed', 0)}`
- **Failed Tests:** `{test_results.get('failed', 0)}`
- **Execution Errors:** `{test_results.get('errors', 0)}`

---

## 📁 Files Reviewed

{files_str}

---

## 🚨 Critical Issues

{criticals_str}

---

## ⚠️ Warnings

{warnings_str}

---

## 💡 Recommendations & Improvements

{infos_str}

---

## 🏗️ Technical Scans Detail

### Architecture Review
- Checked for circular dependencies.
- Analyzed folder naming structure.
- Scanned for unused imports.

### Security Review
- Evaluated SQL queries for raw f-string concatenation risks.
- Checked for shell command injection flags.
- Audited hardcoded secrets/passwords.

### Performance Review
- Scanned for blocking time.sleep operations in async loops.
- Highlighted candidate helper methods missing cache descriptors.
"""
        return report

    def write_report(self, project_path: Path, report_content: str) -> Path:
        """
        Saves the quality report to reports/project_review.md in the project directory.
        """
        report_dir = project_path / "reports"
        report_dir.mkdir(parents=True, exist_ok=True)
        
        report_file = report_dir / "project_review.md"
        with open(report_file, "w", encoding="utf-8") as f:
            f.write(report_content)

        # Also write to top-level for convenience
        with open(project_path / "project_review.md", "w", encoding="utf-8") as f:
            f.write(report_content)

        _logger.info(f"Quality report saved successfully at: {report_file}")
        return report_file
